### ISSUE TITLE
always show sidebar

### ISSUE THREAD

**Issue by hien4990** [Suibs/Tree-Style-Tab-For-Chrome#8]
i want the sidebar always show up, not hidding when mouse doesnt hover the left egde, or open in new tab...
Please add this, thanks.

**Comment by Suibs** [comment]
Hi @hien4990,  this is a commonly raised issue by the community. This is the copied response from the answer:

### Stay open all the time
The reason the tree style tab addon is able to stay open at all times in FF is because of the existence of a built in window that is separate from the webpage - a space dedicated for addons if you may, commonly known as the sidebar. 

On chrome, there isn't such utility which means any extension will have to either modify the content of every webpage to make space for such feature to be enabled. 

The issue is dynamically generated sites will not resize responsively upon modification. 

We've had thoughts on giving it a go regardless but upon accessing the probability of shipping a broken feature to customers, we decided not to proceed.

However, this does not mean the end of attempting to create the best user experience possible. Within the next two weeks, external popup window mode will be available. The progress of the project can be found here: https://trello.com/b/u9Mjyu8s/tree-style-tab-for-google-chrome-roadmap

Thanks!
